spring.application.name=team-task-manager

spring.datasource.url=${JDBC_DATABASE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.h2.console.enabled=true

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000
app.cors.allowed-origin=${FRONTEND_URL}
